/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DriverRouteImport } from './routes/driver'
import { Route as ClientRouteImport } from './routes/client'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverTodayRouteImport } from './routes/driver.today'
import { Route as DriverItineraireRouteImport } from './routes/driver.itineraire'
import { Route as ClientOrderRouteImport } from './routes/client.order'
import { Route as ClientHistoryRouteImport } from './routes/client.history'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminNewOrderRouteImport } from './routes/admin.new-order'
import { Route as AdminDriverViewRouteImport } from './routes/admin.driver-view'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as AdminArchivesRouteImport } from './routes/admin.archives'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRoute = DriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRoute,
} as any)
const DriverTodayRoute = DriverTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => DriverRoute,
} as any)
const DriverItineraireRoute = DriverItineraireRouteImport.update({
  id: '/itineraire',
  path: '/itineraire',
  getParentRoute: () => DriverRoute,
} as any)
const ClientOrderRoute = ClientOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => ClientRoute,
} as any)
const ClientHistoryRoute = ClientHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => ClientRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewOrderRoute = AdminNewOrderRouteImport.update({
  id: '/new-order',
  path: '/new-order',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDriverViewRoute = AdminDriverViewRouteImport.update({
  id: '/driver-view',
  path: '/driver-view',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArchivesRoute = AdminArchivesRouteImport.update({
  id: '/archives',
  path: '/archives',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/archives': typeof AdminArchivesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/driver-view': typeof AdminDriverViewRoute
  '/admin/new-order': typeof AdminNewOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/order': typeof ClientOrderRoute
  '/driver/itineraire': typeof DriverItineraireRoute
  '/driver/today': typeof DriverTodayRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/archives': typeof AdminArchivesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/driver-view': typeof AdminDriverViewRoute
  '/admin/new-order': typeof AdminNewOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/order': typeof ClientOrderRoute
  '/driver/itineraire': typeof DriverItineraireRoute
  '/driver/today': typeof DriverTodayRoute
  '/driver': typeof DriverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/driver': typeof DriverRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/archives': typeof AdminArchivesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/driver-view': typeof AdminDriverViewRoute
  '/admin/new-order': typeof AdminNewOrderRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/client/history': typeof ClientHistoryRoute
  '/client/order': typeof ClientOrderRoute
  '/driver/itineraire': typeof DriverItineraireRoute
  '/driver/today': typeof DriverTodayRoute
  '/driver/': typeof DriverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/client'
    | '/driver'
    | '/login'
    | '/admin/archives'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/driver-view'
    | '/admin/new-order'
    | '/admin/settings'
    | '/client/history'
    | '/client/order'
    | '/driver/itineraire'
    | '/driver/today'
    | '/driver/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/client'
    | '/login'
    | '/admin/archives'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/driver-view'
    | '/admin/new-order'
    | '/admin/settings'
    | '/client/history'
    | '/client/order'
    | '/driver/itineraire'
    | '/driver/today'
    | '/driver'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/client'
    | '/driver'
    | '/login'
    | '/admin/archives'
    | '/admin/catalog'
    | '/admin/clients'
    | '/admin/dashboard'
    | '/admin/driver-view'
    | '/admin/new-order'
    | '/admin/settings'
    | '/client/history'
    | '/client/order'
    | '/driver/itineraire'
    | '/driver/today'
    | '/driver/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  DriverRoute: typeof DriverRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/today': {
      id: '/driver/today'
      path: '/today'
      fullPath: '/driver/today'
      preLoaderRoute: typeof DriverTodayRouteImport
      parentRoute: typeof DriverRoute
    }
    '/driver/itineraire': {
      id: '/driver/itineraire'
      path: '/itineraire'
      fullPath: '/driver/itineraire'
      preLoaderRoute: typeof DriverItineraireRouteImport
      parentRoute: typeof DriverRoute
    }
    '/client/order': {
      id: '/client/order'
      path: '/order'
      fullPath: '/client/order'
      preLoaderRoute: typeof ClientOrderRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/history': {
      id: '/client/history'
      path: '/history'
      fullPath: '/client/history'
      preLoaderRoute: typeof ClientHistoryRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new-order': {
      id: '/admin/new-order'
      path: '/new-order'
      fullPath: '/admin/new-order'
      preLoaderRoute: typeof AdminNewOrderRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/driver-view': {
      id: '/admin/driver-view'
      path: '/driver-view'
      fullPath: '/admin/driver-view'
      preLoaderRoute: typeof AdminDriverViewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/archives': {
      id: '/admin/archives'
      path: '/archives'
      fullPath: '/admin/archives'
      preLoaderRoute: typeof AdminArchivesRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminArchivesRoute: typeof AdminArchivesRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminDriverViewRoute: typeof AdminDriverViewRoute
  AdminNewOrderRoute: typeof AdminNewOrderRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminArchivesRoute: AdminArchivesRoute,
  AdminCatalogRoute: AdminCatalogRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminDriverViewRoute: AdminDriverViewRoute,
  AdminNewOrderRoute: AdminNewOrderRoute,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientHistoryRoute: typeof ClientHistoryRoute
  ClientOrderRoute: typeof ClientOrderRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientHistoryRoute: ClientHistoryRoute,
  ClientOrderRoute: ClientOrderRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface DriverRouteChildren {
  DriverItineraireRoute: typeof DriverItineraireRoute
  DriverTodayRoute: typeof DriverTodayRoute
  DriverIndexRoute: typeof DriverIndexRoute
}

const DriverRouteChildren: DriverRouteChildren = {
  DriverItineraireRoute: DriverItineraireRoute,
  DriverTodayRoute: DriverTodayRoute,
  DriverIndexRoute: DriverIndexRoute,
}

const DriverRouteWithChildren =
  DriverRoute._addFileChildren(DriverRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  DriverRoute: DriverRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
